### ISSUE TITLE
Image elements in a profile_COMMON don't work

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/COLLADA2GLTF#114] opened 2017-12-23 23:08 UTC
Replaces https://github.com/KhronosGroup/glTF/issues/340

If an image is defined in the profile instead of in the library_images the image ends up in the gltf with a empty source.

**Comment by lasalvavida** [comment] 2018-04-26 15:29
#129 is a duplicate of this. When it is resolved, this can be closed.

**Closed** 2018-08-30 01:10 UTC
Labels: bug
