### ISSUE TITLE
error when convert dae to gltf 

### ISSUE THREAD

**Issue by DamonsJ** [KhronosGroup/COLLADA2GLTF#256] opened 2019-07-25 02:43 UTC
I have dae models which are attached in kmz file (see attachment)
I want to convert to these dae models to gltf using GOLLADA2GLTF-bin.exe, but the result gltf can not open.
My system is Windows 10  and the GOLLADA2GLTF-bin.exe is downloaded from https://github.com/KhronosGroup/COLLADA2GLTF/releases version 2.1.5

the command line I used to convert dae models is   "GOLLADA2GLTF-bin.exe  1EMD_WTG_3DA_7280.dae test.gltf"

when I convert these models using  this tool :https://cesiumjs.org/convertModel/, it give me right result. 
I don't know where is the problem?

[093ce7f0-adc3-11e9-b0b8-d89ef33c3506.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/3429522/093ce7f0-adc3-11e9-b0b8-d89ef33c3506.zip)

**Comment by DamonsJ** [comment] 2019-07-29 02:33
what if the model have degenrated faces?

**Comment by DamonsJ** [comment] 2019-08-12 06:26
why nobody give me a hint?

**Comment by lasalvavida** [comment] 2019-08-18 22:04
Hi @DamonsJ,

There's a few things going on here.

Your COLLADA models have .bmp textures. This is not a supported texture format for glTF. That being said, it looks like your textures are a flat gray color anyway, so you could probably just omit them. If you don't want to do that, you can convert your .bmp textures to .png or .jpeg.

Because the textures have a relative path "../images", I suspect you are using the drag and drop converter without dragging the texture along as well. When you do this, the online converter is generating a default material for your model because the texture is missing.

Your exporter (WindPRO 3.0.654?) is making a pretty common mistake in your COLLADA material (that the drag and drop converter is leaving out because it is creating a default material):

```xml
<transparency>
    <float>0.000000</float>
</transparency>
```

You can read more here if you are interested: https://github.com/mrdoob/three.js/issues/2210

Many exporters mistakenly specify 0 when they mean for a model to be fully opaque. Early versions of SketchUp made this mistake and proliferated it to other COLLADA exporters before it was fixed.

We detect SketchUp versions and correct this because it is a pretty popular exporter, but we can't do this for every exporter that outputs invalid COLLADA. The converter is working as intended.

I'm going to close this since this isn't an issue with the converter, but I'm happy to answer any other questions in this thread if you have any.

**Closed by lasalvavida** 2019-08-18 22:04 UTC

**Comment by DamonsJ** [comment] 2019-08-20 02:54
@lasalvavida Thanks a lot!
Yes, I drag the COLLADA  models to the converter.
My question is how can I generate a right gltf model? change bmp to png/jpeg?

**Comment by DamonsJ** [comment] 2019-08-20 03:06
and after I convert bmp to png/jpeg , the result gltf is wrong, it appears gltf have no mesh
